version: '3.6'

services:
    mysql:
        # for mysql v8 we would want PR merged here for node https://github.com/mysqljs/mysql/pull/1962 + release
        # and pdo for PHP should support mysql 8 (new authentication plugins) - this seems to be unnecessary hassle otherwise (http://php.net/manual/en/ref.pdo-mysql.php)
        image: mysql:5
        volumes:
            - ./db-data:/var/lib/mysql:rw
        env_file:
            - ./shared/.env
        networks:
            - api
            - app

    api:
        build:
            context: ./api
            dockerfile: ./_docker/php/Dockerfile
        depends_on:
            - mysql
        env_file:
            - ./shared/.env
            - ./api/.env
        volumes:
            - ./api/_docker/php/www.conf:/usr/local/etc/php-fpm.d/99-www.conf
        restart: on-failure
        networks:
            - api

    nginx:
        image: silverbackis/nginx:symfony4
        depends_on:
            - api
        env_file:
            - ./shared/.env
        networks:
            - api

    varnish:
        image: silverbackis/varnish:symfony4
        depends_on:
            - nginx
            - api
        networks:
            - api
            - app

    app:
        build:
            context: ./app
            dockerfile: ./_docker/Dockerfile
        env_file:
            - ./shared/.env
            - ./app/.env
        networks:
            - app

volumes:
    db-mysql:

networks:
    app:
    api: