version: '3.6'

services:
    mysql:
        ports:
            - "4306:3306"

    php:
        volumes:
            - ./api:/srv/api:rw,cached
            # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
            # - ./api/var:/srv/api/var:rw

    nginx:
        environment:
            - CORS_HOST="https?://(serve.b-w.uk|localhost):?[0-9]*"
        volumes:
            - ./api/public:/srv/api/public:ro
        ports:
            - "8080:80"

    varnish:
        ports:
            - "8081:80"

    app:
        ports:
            - "80:3000"
